# chrome.exe --user-data-dir="C:/Chrome dev session" --disable-web-security
openapi: 3.0.0
info:
  title: Employee Management API
  version: 1.0.0
  description: API for managing employees by Shubham Yadav
  contact:
    email: "shubhamyadav.cdac@gmail.com"
servers:
  - url: http://localhost:8080

paths:
  /employees:
    get:
      summary: List all employees
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Employee"

    post:
      summary: Create a new employee
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Employee"
      responses:
        "201":
          description: Employee created successfully

  /employees/{id}:
    get:
      summary: View employee by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Employee"
        "404":
          description: Employee not found

    put:
      summary: Update employee by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Employee"
      responses:
        "200":
          description: Employee updated successfully
        "404":
          description: Employee not found

    delete:
      summary: Delete employee by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: Employee deleted successfully
        "404":
          description: Employee not found

components:
  schemas:
    Employee:
      type: object
      properties:
        id:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        password:
          type: string
        phoneNo:
          type: string
        role:
          type: string
